### ISSUE TITLE
After installing TinyMCE Strapi Marketplace stops working

### ISSUE THREAD

**Issue by webkwondo** [SKLINET/strapi-plugin-tinymce#19] opened 2023-01-17 11:08 UTC
Hello!

After installing TinyMCE plugin Strapi Marketplace stops working. More precisely after adding plugin code to middlewares.ts 

If I remove plugin code from middlewares.ts marketplace works normally 

The same error occurs on both Node v16.17.0 (on Windows, Strapi v4.4.3) and Node v18.12.1 (on Mac, Strapi v4.5.6).

Strapi with Typescript and Postgresql (14 and 15)

<img width="1138" alt="Screenshot 2023-01-17 at 11 54 24" src="https://user-images.githubusercontent.com/36866326/212853373-bd828b4c-387f-426d-80a9-98b00a841355.png">

**Comment by maksymenkoml** [comment] 2023-03-11 02:43
Same here

**Comment by Sklico** [comment] 2023-04-13 13:54
I'm closing this as it's duplicate of this issue https://github.com/SKLINET/strapi-plugin-tinymce/issues/14

**Closed by Sklico** 2023-04-13 13:54 UTC
